spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://db:5432/order_service
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.liquibase.default-schema=public
spring.liquibase.clear-checksums=true
spring.jpa.show-sql=true

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

server.port=8081
